### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by AmirAlOmari** [btroncone/ngrx-store-localstorage#248]
Since Angular 16 is [released](https://github.com/angular/angular/releases/tag/16.0.0), it would be great to bring the support :raised_hands:

**Comment by BBlackwo** [comment]
Anyone is welcome to raise a PR similar to #237 :slightly_smiling_face: 

# Steps

1. Follow https://update.angular.io/?v=14.0-15.0

2. Upgrade `ngrx/store`, `ng-packagr `, and maybe `typescript` (or any other libraries that are required)

3. Upgrade peer dependencies in `projects/lib/package.json`

4. Make sure commit message has `BREAKING CHANGE` in it to do a major bump

**Comment by yngvebn** [comment]
> 4\. BREAKING CHANGE

Gotcha! I'm pretty sure I did the required steps you outline :)

**Comment by sream** [comment]
Any updates regarding the release?

**Comment by yngvebn** [comment]
> Any updates regarding the release?

I'm waiting for @BBlackwo to take a look at my [PR](https://github.com/btroncone/ngrx-store-localstorage/pull/251). Shouldn't be anything more that's required for this. This is also blocking our upgrade...

**Comment by sream** [comment]
I've force installed the current version. It's working but if the changes don't get merged/built until the end of the week I'll just fork your PR and publish it in-house.

**Comment by BBlackwo** [comment]
:tada: This issue is fixed in version 16.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ngrx-store-localstorage/v/16.0.0)
- [GitHub release](https://github.com/btroncone/ngrx-store-localstorage/releases/tag/v16.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
