### ISSUE TITLE
Format of date strings change after rehydration

### ISSUE THREAD

**Issue by haugero** [btroncone/ngrx-store-localstorage#31]
We store dates like "2017-05-03T16:17:05" as strings in our store.
We use your localStorageSync with rehydrate=true.
After reloading our angular application the rehydrated initial state shows that the date string has been changed to "2017-05-03T14:17:05.000Z"

If I read the following issue I know why this is the case
https://github.com/btroncone/ngrx-store-localstorage/issues/3

But do you know how I could prevent that my date strings are getting converted?

We use "ngrx-store-localstorage": "0.1.5"

**Comment by ernestomancebo** [comment]
hi @haugero,

I'd say it's a timezone issue, since when it's rehydrated a 'Z' is appended. It seems to be capturing the date at UTC, then converted to the browser timezone or vice versa.

A workaround would be passing an object instead the name of the store you'd like to keep on sync, in that object, pass a reviver function that returns the same value and avoid the parsing that the default reviver function does.

Here's how:

```ts
localStorageSync([{
	todos: ['fieldA', 'dateField', 'others fields you want to keep on sync'],
	reviver: (val) => val
}],
true);
```

**Comment by btroncone** [comment]
Closing this issue.
