### ISSUE TITLE
Upgrade to ngrx 4.0.0

### ISSUE THREAD

**Issue by kucharzyk** [btroncone/ngrx-store-localstorage#41]
ngrx/store 4.0.0 was released today but ngrx-store-localstorage still has dependency to ^2.2.1 version

**Comment by richnologies** [comment]
I think with changes in ngrx/store@4, this middleware can now be implemented as a metareducer.

I build a very simplistic version as a temporary solution I share on this Gist.

https://gist.github.com/richnologies/9495211d986b15d6345e216436d6367f

I prefer to wait until this library updates rather than create a new one and I am willing to help

Hope the gist could help

**Comment by sutkovoy** [comment]
Any updates on it?

**Comment by davideberlein** [comment]
@richnologies just a litte comment on your solution: You are using 'rehydratate' instead of 'rehydrate' in your config. Apart from that it works really well, thanks for the snippet!

**Comment by richnologies** [comment]
@davideberlein thanks. It's fixed now

**Comment by btroncone** [comment]
Sorry for the delay, I bumped the dep to 4.0.0. Good luck!

@richnologies This is already a meta-reducer. 👍
