### ISSUE TITLE
localForage

### ISSUE THREAD

**Issue by xban1x** [btroncone/ngrx-store-localstorage#48]
I believe the next iteration step for this library should be to implement localForage as a means for us to be able to choose different storage options.

**Comment by uitgewis** [comment]
It's already possible for users to use their own storage mechanisms via the optional `storage` configuration option.

**Comment by brettatoms** [comment]
The problem is localForage uses an async API so it doesn't technically implement the Storage API and isn't a drop in replacement here. The natural-apptitude/ngrx-store-ionic-storage project, which claims to be inspired by this project, does the async call in the meta reducer which doesn't seem right and I would think is a race condition just waiting to happen.

Here's is the where I asked about this in the ngrx/store gitter channel: https://gitter.im/ngrx/store?at=59b92227cfeed2eb6503c374

**Comment by btroncone** [comment]
@brettatoms If you need to utilize an async API to sync state I would recommend moving this to an effect.
